"""empty message

Revision ID: 54eea4ade82e
Revises: 67f6049813cd
Create Date: 2025-10-25 23:46:04.046114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54eea4ade82e'
down_revision = '67f6049813cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('50')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('route_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('50', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
